### ISSUE TITLE
Add Sensor Identification

### ISSUE THREAD

**Issue by bradh** [stac-extensions/video#17]
I think there could be two sensor identification things you'd want to add - a generic make/model, and a unique identifier.

In MISB terms, the first would map to ST 0601.17 Item 11 (Image Source Sensor), and the second would map to ST 0601.17 Item 94 (MIIS Core Identifier). Similar concepts occur in other places too.

It could be worth breaking out the MIIS Core Identifier into the platform and sensor parts (see ST 1204), but I'm not decided on that. It feels like it could be too "MISB" for something that should be more general. Possibly the way to handle that would be to allow key-value pairs below the top-level opaque identifier.

**Comment by darrenwiens** [comment]
Sorry for the delay. Would you mind posting links to the relevant sections of the standards?

**Comment by darrenwiens** [comment]
Added in: https://github.com/stac-extensions/video/pull/19
