### ISSUE TITLE
video:miis_core_id details

### ISSUE THREAD

**Issue by m-mohr** [stac-extensions/video#21]
Could you add some additional information for the video:miis_core_id? What is MIIS? What is MISB ST 0601.17.94? Maybe some links would help. As a non-video expert, I don't understand what this is all about.

**Comment by darrenwiens** [comment]
Sure, I added a link to the MISB ST 0601.17 metadata spec landing page: https://nsgreg.nga.mil/doc/view?i=5093

I wouldn't say I'm a video expert either, but this ID seems to be well-known in the wild: https://github.com/stac-extensions/video/issues/17
